spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false  #关闭自我保护模式，可快速删除注册
    eviction-interval-timer-in-ms: 30000 #刷新间隔
